FERNET_KEY = "syb5NarG-hqaV6uOhcPZeV55HgG_689C7PgdxoCJtkU="

OPENAI_API_KEY = "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"

HUGGINGFACE_TOKEN = "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"


APP_USERNAME = "provider1"
APP_PASSWORD = "password123"

[azure_openai]
api_key = "5qFAHAw1FLN4wxlWWZajLmBQxWSrhqjjLxbSvigWwzWVgUyG5JqeJQQJ99BHACYeBjFXJ3w3AAABACOG6CPD"
endpoint = "https://aimedscriptor.openai.azure.com/"
deployment_name = "medscriptor"
api_version = "2025-01-01-preview"

